In [ ]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("../data/insurance.csv")

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [4]:
df = pd.get_dummies(df, drop_first=True)

df.head()

,age,bmi,children,charges,sex_male,smoker_yes,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,False,True,False,False,True
1,18,33.770,1,1725.55230,True,False,False,True,False
2,28,33.000,3,4449.46200,True,False,False,True,False
3,33,22.705,0,21984.47061,True,False,True,False,False
4,32,28.880,0,3866.85520,True,False,True,False,False

In [5]:
X = df.drop("charges", axis=1)
y = df["charges"]

print(X.shape)
print(y.shape)

(1338, 8)
(1338,)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(1070, 8)
(268, 8)

In [7]:
base_model = DecisionTreeRegressor(max_depth=4)

model = AdaBoostRegressor(
    estimator=base_model,
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)

model.fit(X_train, y_train)

AdaBoostRegressor(estimator=DecisionTreeRegressor(max_depth=4),
                  learning_rate=0.1, n_estimators=100, random_state=42)

In [8]:
y_pred = model.predict(X_test)

y_pred[:5]

array([14210.85358359,  7126.8219458 , 26832.21283724, 13884.07581803,
       35368.78674931])

In [9]:
mae = mean_absolute_error(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, y_pred)

print("MAE :", mae)
print("MSE :", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE : 4088.2208356325577
MSE : 26242246.06872901
RMSE: 5122.718620881788
R2 Score: 0.8309664380728318

In [10]:
with open("../models/adaboost_model.pkl", "wb") as f:
    pickle.dump(model, f)

print("Model Saved Successfully!")

Model Saved Successfully!

In [11]:
with open("../models/adaboost_model.pkl", "rb") as f:
    loaded_model = pickle.load(f)

sample = X_test.iloc[:1]

prediction = loaded_model.predict(sample)

print("Prediction:", prediction)

Prediction: [14210.85358359]

In [12]:
importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": model.feature_importances_
})

importance.sort_values(
    by="Importance",
    ascending=False
)

            Feature  Importance
4        smoker_yes    0.632742
1               bmi    0.196005
0               age    0.140474
2          children    0.020846
7  region_southwest    0.007262
6  region_southeast    0.001312
3          sex_male    0.000860
5  region_northwest    0.000499